/* Named re-exports - no wildcard barrels (project convention) */

export type {
  CreateHIP4AdapterConfig,
  HIP4ClientConfig,
  HIP4Signer,
  HLCancelResponse,
  HLCancelStatus,
  HLCandle,
  HLClearinghouseState,
  HLDelegatorSummary,
  HLDeployerEntry,
  HLExtraAgent,
  HLFill,
  HLFrontendOrder,
  HLKeywordHint,
  HLLedgerDelta,
  HLLedgerUpdate,
  HLMergeOutcomeAction,
  HLMergeQuestionAction,
  HLMultiSigSigners,
  HLNegateOutcomeAction,
  HLOutcome,
  HLOutcomeMeta,
  HLOutcomeTemplate,
  HLQuestion,
  HLReferralState,
  HLScheduleCancelAction,
  HLSettledOutcome,
  HLSignature,
  HLSpotClearinghouseState,
  HLSplitOutcomeAction,
  HLTemplateRole,
  HLTemplateRoleKind,
  HLUserAbstraction,
  HLUserFees,
  HLUserOutcomeAction,
  HLUserRoleResponse,
  HLWebData3,
  HLWsActivePerpAssetCtxData,
  HLWsActiveSpotAssetCtxData,
  HLWsAllMidsData,
  HLWsBboData,
  HLWsClearinghouseStateEvent,
  HLWsL2BookData,
  HLWsOpenOrdersEvent,
  HLWsOutcomeMetaSideSpec,
  HLWsOutcomeMetaUpdate,
  HLWsOutcomeMetaUpdates,
  HLWsOutcomeSpec,
  HLWsQuestionSpec,
  HLWsSpotAssetCtxItem,
  HLWsSpotAssetCtxsData,
  HLWsSpotStateEvent,
  HLWsTradesEvent,
  HLWsUserFillsEvent,
  MergeOutcomeParams,
  MergeQuestionParams,
  NegateOutcomeParams,
  ParsedDescription,
  ParsedPriceBucketDescription,
  PredictionAccountAdapter,
  PredictionAuthAdapter,
  PredictionEventAdapter,
  PredictionMarketDataAdapter,
  PredictionsAdapter,
  PredictionTradingAdapter,
  PredictionWalletAdapter,
  PriceBinaryMarket,
  QuestionIndex,
  SplitOutcomeParams,
  SpotSendParams,
  Unsubscribe,
  UsdClassTransferParams,
  UsdSendParams,
  WalletActionResult,
  WithdrawParams,
} from "./adapter";
/* v2: Pricing utilities */
/* v2: Market discovery */
/* v2: Market classification */
/* v2: Coin helpers */
export {
  buildQuestionIndex,
  classifyAllOutcomes,
  classifyOutcome,
  computeTickSize,
  createHIP4Adapter,
  discoverPriceBinaryMarkets,
  formatMarketLabel,
  formatPredictionPrice,
  formatPrice,
  ALL_DEXS,
  getAgentApprovalTypedData,
  getBuilderFeeApprovalTypedData,
  getMinShares,
  getPriceBucketBounds,
  HIP4Client,
  HIP4EventAdapter,
  AGENT_DOMAIN,
  AGENT_TYPES,
  bytesToHex,
  createL1ActionHash,
  HIP4Auth,
  HIP4TradingAdapter,
  HIP4WalletAdapter,
  HLApiError,
  isUsdClassTransferRequired,
  MIN_NOTIONAL,
  normalizeSignature,
  outcomeCoin,
  parseDescription,
  parsePriceBucketDescription,
  parseOutcomeCoin,
  parseSideCoin,
  periodMinutes,
  roundToTick,
  sideAssetId,
  sideCoin,
  splitHexSignature,
  stripZeros,
  submitAgentApproval,
  submitBuilderFeeApproval,
  timeToExpiry,
  USDC_HL_TOKEN_MAINNET,
  USDC_HL_TOKEN_TESTNET,
  USDH_ASSET_ID,
  USDH_ASSET_ID_MAINNET,
  USDH_ASSET_ID_TESTNET,
  USDH_CORE_DECIMALS,
  USDH_EVM_ADDRESS_MAINNET,
  USDH_EVM_ADDRESS_TESTNET,
  USDH_EVM_DECIMALS,
  USDH_HL_TOKEN_MAINNET,
  USDH_HL_TOKEN_TESTNET,
  USDH_SPOT_INDEX_MAINNET,
  USDH_SPOT_INDEX_TESTNET,
  USDH_SPOT_PAIR,
  USDH_SPOT_PAIR_MAINNET,
  USDH_SPOT_PAIR_TESTNET,
  USDH_TOKEN_HASH_MAINNET,
  USDH_TOKEN_HASH_TESTNET,
  USDH_TOKEN_INDEX_MAINNET,
  USDH_TOKEN_INDEX_TESTNET,
  deriveCoreEvmSystemAddress,
  HYPE_CORE_EVM_SYSTEM_ADDRESS,
  MAX_CORE_EVM_TOKEN_INDEX,
  CORE_TO_EVM_GAS_LIMIT,
  estimateCoreToEvmFee,
  medianBaseFeeWei,
  type CoreToEvmFeeBreakdown,
  type CoreToEvmFeeInputs,
  findHypeUsdcSpotPairCoin,
  HYPE_USDC_SPOT_INDEX_MAINNET,
  HYPE_USDC_SPOT_INDEX_TESTNET,
  HYPE_USDC_SPOT_PAIR_MAINNET,
  HYPE_USDC_SPOT_PAIR_TESTNET,
  selectHypeSpotMarkPx,
  type SelectHypeSpotMarkPxOptions,
  type SpotMetaShape,
} from "./adapter";

/* Deployer surface (experimental): registration, settlement, agents, multi-sig */
export {
  ABSTRACTION_WIRE_VALUES,
  activeAgents,
  agentStatus,
  AGENT_APPROVAL_MAX_DAYS,
  APPROVE_AGENT_TYPES,
  assertTemplateInstance,
  BASE_TAKER_RATE,
  buildActivateDeployerAction,
  buildApproveAgentAction,
  buildCDepositAction,
  buildConvertToMultiSigUserAction,
  buildCWithdrawAction,
  buildDeactivateDeployerAction,
  buildMultiSigAction,
  buildOutcomeSettlement,
  buildRegisterQuestionAction,
  buildRegisterStandaloneOutcomeAction,
  buildSettleOutcomeAction,
  buildSettleQuestionAction,
  buildTokenDelegateAction,
  buildUserSetAbstractionAction,
  canDeploy,
  canonicalKeywords,
  CONVERT_TO_MULTI_SIG_USER_TYPES,
  C_DEPOSIT_TYPES,
  C_WITHDRAW_TYPES,
  deployBlockedReason,
  DeployerError,
  deployerSteps,
  DEPLOYER_LIMITS,
  eventAtFrom,
  EVENT_KEYWORDS,
  expiringAgents,
  feeAmounts,
  feeSplit,
  FEE_SCALE_MAX,
  FEE_SCALE_MIN,
  findAgent,
  findTemplate,
  HIP4DeployerAdapter,
  hypeToWei,
  HYPE_WEI_DECIMALS,
  instanceDescription,
  isDeployerAbstraction,
  KEYWORD_ALIASES,
  KEYWORD_HINTS,
  lowerAddress,
  MAX_KEYWORD_HORIZON_MS,
  minimalSignatureHex,
  multiSigActionHash,
  multiSigPayloadAction,
  namedOutcomeTemplates,
  NAMED_AGENT_SLOTS,
  nextNonce,
  normalizeFeeScale,
  normalizeSettleFraction,
  normalizeVenueName,
  parseInstanceDescription,
  parseSeriesId,
  perpFrom,
  PERP_KEYWORDS,
  questionByOutcome,
  parseTemplateStamp,
  placeholdersIn,
  readDeployedOutcome,
  readDeployedOutcomes,
  readDeployerSnapshot,
  renderTemplateText,
  requireTemplate,
  resolutionDeadlineFrom,
  RESOLUTION_DEADLINE_KEYWORDS,
  scalarBandFrom,
  SEND_MULTI_SIG_TYPES,
  seriesFacts,
  settlementQueue,
  settlementStatus,
  signatureChainId,
  signMultiSigEnvelope,
  signMultiSigInnerL1Action,
  signMultiSigInnerUserSignedAction,
  sortedKeywordPairs,
  splitBySeries,
  suggestPriceSettlement,
  supersededBy,
  templateIdOfOutcome,
  templateParentId,
  templateRoleKind,
  templateSideNames,
  thresholdFrom,
  THRESHOLD_KEYWORDS,
  TOKEN_DELEGATE_TYPES,
  toTemplateStamp,
  unfillablePlaceholders,
  userSignedEnvelope,
  USER_SET_ABSTRACTION_TYPES,
  validateKeywordValue,
  validateTemplateInstance,
  venueNameError,
  VENUE_NAME_RE,
  withMultiSigTypes,
} from "./deployer";
export type {
  AgentStatus,
  ApproveAgentParams,
  BuildMultiSigActionParams,
  ConvertToMultiSigUserParams,
  DeployedOutcome,
  DeployerActionResult,
  DeployerLimits,
  DeployerSnapshot,
  DeployerStep,
  DeployerStepsOptions,
  Eip712Fields,
  Eip712Types,
  FeeSplit,
  HIP4DeployerAdapterOptions,
  HLAbstractionSetting,
  HLAccountAction,
  HLActivateOutcomeDeployerAction,
  HLApproveAgentAction,
  HLCDepositAction,
  HLConvertToMultiSigUserAction,
  HLCWithdrawAction,
  HLDeployerAction,
  HLMultiSigAction,
  HLNetwork,
  HLOutcomeSettlement,
  HLRegisterQuestionAction,
  HLRegisterStandaloneOutcomeAction,
  HLSettleOutcomeAction,
  HLSettleQuestionAction,
  HLTemplateInstance,
  HLTokenDelegateAction,
  HLUserSetAbstractionAction,
  HLUserSignedEnvelope,
  MultiSigInnerParams,
  ReadDeployerSnapshotOptions,
  RegisterQuestionParams,
  RegisterStandaloneOutcomeParams,
  SeriesFacts,
  SeriesId,
  SettleableOutcome,
  SettlementState,
  SettlementStatus,
  SettlementSuggestion,
  SettlementWindow,
  SettleQuestionParams,
  TemplateProblem,
  ValidateKeywordOptions,
} from "./deployer";

/* Liquidity rewards (season-scoped eligibility + rewards checks) */
export type {
  CheckEligibilityParams,
  CheckRewardsParams,
  EligibilitySubject,
  LiquidityRewardsChampionMarket,
  LiquidityRewardsEpochStatus,
  LiquidityRewardsMatchMarket,
  LiquidityRewardsMid,
  LiquidityRewardsScore,
  LiquidityRewardsScoredOutcome,
  LiquidityRewardsSeasonHandle,
  LiquidityRewardsSeasonId,
  LiquidityRewardsSnapshot,
  MatchesEligibility,
  RewardsCheckResult,
  TeamsEligibility,
} from "./liquidity-rewards";
export {
  LIQUIDITY_REWARDS_CONFIG,
  liquidityRewards,
  LiquidityRewardsError,
} from "./liquidity-rewards";

/* Streams */
export type { PriceFeedCandle } from "./streams/candle-utils";
export {
  candleBoundaryMs,
  intervalToMs,
  processTick,
} from "./streams/candle-utils";
export type {
  PerpPriceFeedOptions,
  PerpPriceFeedSnapshot,
} from "./streams/perp-price-feed";
export { createPerpPriceFeed } from "./streams/perp-price-feed";
export type { PriceFeedOptions, PriceFeedSnapshot } from "./streams/price-feed";
export { createPriceFeed } from "./streams/price-feed";
export type {
  PredictionActivity,
  PredictionAuthState,
  PredictionPosition,
} from "./types/account";
/* Types */
export type {
  PredictionCategory,
  PredictionEvent,
  PredictionEventStatus,
  PredictionMarket,
  PredictionOutcome,
} from "./types/event";
/* v2: HIP4Market types */
export type {
  BaseMarket,
  DefaultBinaryMarket,
  FetchMarketsParams,
  FetchMarketsResult,
  HIP4Market,
  LabelledBinaryMarket,
  MarketSide,
  MarketsByQuestion,
  MarketsByType,
  MarketType,
  MultiOutcomeMarket,
  PriceBucketMarket,
} from "./types/hip4-market";
export type {
  PredictionOrderBook,
  PredictionOrderBookLevel,
  PredictionPrice,
  PredictionTrade,
} from "./types/market";
export type {
  PredictionCancelParams,
  PredictionModifyParams,
  PredictionOrderParams,
  PredictionOrderResult,
  PredictionBatchOrderResult,
} from "./types/trading";

/* Orderbook utilities */
export type { TradeCostResult } from "./utils/orderbook";
export {
  computeEstimatedCost,
  computePotentialReturn,
  computeTradeCost,
} from "./utils/orderbook";
